webimage_extra_packages:
  - syslog-ng

web_extra_daemons:
  - name: 'syslog-ng'
    command: '/usr/bin/sudo /usr/sbin/syslog-ng -F --no-caps'
    directory: /var/www/html

web_environment:
  - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-grafana:4318
