services:
  web:
    volumes:
      # Permissions of this volume are enforced by the
      # web-entrypoint.d/ddev-grafana-fix-log-directory-permissions.sh file
      # because supervisord requires write permission for the current user.
      - web-logs-data:/var/log

  grafana-loki:
    image: grafana/loki:latest
    user: '${UID:-}:${GID:-}'
    container_name: 'ddev-${DDEV_SITENAME}-grafana-loki'
    volumes:
      - type: bind
        source: ./grafana/loki/loki.yaml
        target: /etc/loki/local-config.yaml
      - grafana-loki-data:/data
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=3100:3100
      - HTTPS_EXPOSE=3100:3100

volumes:
  grafana-loki-data:
    name: 'ddev-${DDEV_SITENAME}_grafana-loki-data'
