services:
  tempo:
    container_name: "ddev-${DDEV_SITENAME}-tempo"
    image: grafana/tempo:latest
    user: "${UID:-}:${GID:-}"
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - type: bind
        source: ./grafana/tempo/tempo.yaml
        target: /etc/tempo.yaml
      - tempo-data:/data
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=4318:4318,9411:9411,14268:14268
      - HTTPS_EXPOSE=4318:4318,9411:9411,14268:14268

volumes:
  tempo-data:
    name: "ddev-${DDEV_SITENAME}_tempo"
