services:
  grafana-tempo:
    container_name: 'ddev-${DDEV_SITENAME}-grafana-tempo'
    image: grafana/tempo:latest
    user: '${UID:-}:${GID:-}'
    command:
      - '-config.file=/etc/tempo.yaml'
    volumes:
      - type: bind
        source: ./grafana/tempo/tempo.yaml
        target: /etc/tempo.yaml
      - grafana-tempo-data:/data
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME

volumes:
  grafana-tempo-data:
    name: 'ddev-${DDEV_SITENAME}_grafana-tempo-data'
