# Use this config to bind all services to the localhost of the web container.

version: '3.6'

services:
  prometheus:
    network_mode: container:ddev-${DDEV_SITENAME}-web

  loki:
    network_mode: container:ddev-${DDEV_SITENAME}-web

  tempo:
    network_mode: container:ddev-${DDEV_SITENAME}-web

  grafana:
    # Required to connect from Grafana container via named hosts.
    links:
      - "web:prometheus"
      - "web:loki"
      - "web:tempo"

  web:
    # # This port mapping is better to implement via web_extra_exposed_ports in
    # # the ddev config, but keep them commented here as example.
    # ports:
    #   - 8080 # A frontend app port - will be forwarded by router settings.
    #   - 9090 # Prometheus metrics receiver port - will be forwarded by router settings.
    #   - 3100 # Loki log collector port - will be forwarded by router settings.
    #   - 3200 # The Tempo main API port - will be forwarded by router settings.

    #   # Telemetry and traces, spans collector ports by protocol:
    #   # - 4318 # Tempo OTLP/HTTP port - will be forwarded by router settings.
    #   - 4317 # Tempo OTLP/gRPC port
    #   # - 9411 # Tempo Zipkin/HTTP port - will be forwarded by router settings.
    #   - 14250 # Tempo Jaeger/gRPC port
    #   # - 14268 # Tempo Jaeger/HTTP port - will be forwarded by router settings.
    #   - 6831 # Tempo Jaeger/Compact (UDP) port
    #   # - 55678 # Tempo OpenCensus port - will be forwarded by router settings.

    extra_hosts:
      - "prometheus:127.0.0.1"
      - "loki:127.0.0.1"
      - "tempo:127.0.0.1"

    # # Another approach to expose HTTP tracing endpoints to the ddev host.
    # # Only HTTP endoinds supported via this approach.
    # labels:
    #   com.ddev.site-name: ${DDEV_SITENAME}
    #   com.ddev.approot: $DDEV_APPROOT
    # environment:
    #   - VIRTUAL_HOST=$DDEV_HOSTNAME
    #   # We need also to pass DDEV default ports here via adding the substring:
    #   # ${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}
    #   - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,4318:4318,9411:9411,14268:14268
