apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: Tempo
          matcherRegex: "trace_id=\"(\\w+)\""
          name: trace_id
          url: "$${__value.raw}"

  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: prometheus

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      tracesToLogsV2:
        # Field with an internal link pointing to a logs data source in Grafana.
        # datasourceUid value must match the uid value of the logs data source.
        datasourceUid: "loki"
        spanStartTimeShift: "1h"
        spanEndTimeShift: "-1h"
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{job="syslog"} | logfmt | trace_id="$${__span.traceId}"'
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: "loki"
      spanBar:
        type: "Tag"
        tag: "http.path"
