global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: "tempo"
    static_configs:
      - targets:
          - "tempo:3200"

## Uncomment to enable scraping metrics from the web service by /metrics url.
#   - job_name: "web"
#     static_configs:
#       - targets:
#           - "web:80"
